import type { NextPage } from "next"
import Head from "next/head"
import HomeButton from "../layout/home/HomeButton"
import Navbar from "../layout/navbar/Navbar"
import styles from "./index.module.scss"
import Categories from "../layout/home/Categories"
import FeaturedPlants from "../layout/home/FeaturedPlants"
import CustomerFeatures from "../layout/home/CustomerFeatures"

export default function Home() {
    return (
        <>
            <Navbar />
            <Head>
                <title>Plants - Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <section className={styles.section}>
                    <div className={styles.container}>
                        <h1 className={styles.title}>
                            <span>The</span>
                            <br />
                            Plants
                            <br />
                            Store
                        </h1>
                        <p className={styles.subtitle}>We love plants like you do</p>
                        <p className={styles.desc}>
                            Explore our growing collection of plants, wholeheartedly selected and maintained with care by us -
                            plant lovers.
                        </p>
                        <p className={styles.desc}>Every plant, even exotic ones, available at your home in just 2 days.</p>
                        <HomeButton text="Go shopping" />
                    </div>
                </section>
                <FeaturedPlants />
                <Categories />
                <CustomerFeatures />
            </main>
        </>
    )
}
